# Generated by Django 2.2 on 2023-03-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTimeChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.IntegerField()),
                ('asset_ip', models.CharField(max_length=20)),
                ('server_name', models.CharField(max_length=50)),
                ('time_synced', models.BooleanField()),
                ('verify_time', models.DateTimeField(auto_now_add=True)),
                ('adjusted', models.BooleanField()),
                ('inspector', models.CharField(max_length=20)),
            ],
        ),
    ]
